/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-04-24 10:31:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/CommonHeader.jsp", Long.valueOf(1492850707129L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h2>Wheelskart Login</h2>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>\r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write(".dropdown-menu > li.kopie > a {\r\n");
      out.write("    padding-left:5px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dropdown-submenu {\r\n");
      out.write("    position:relative;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-submenu>.dropdown-menu {\r\n");
      out.write("   top:0;left:100%;\r\n");
      out.write("   margin-top:-6px;margin-left:-1px;\r\n");
      out.write("   -webkit-border-radius:0 6px 6px 6px;-moz-border-radius:0 6px 6px 6px;border-radius:0 6px 6px 6px;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(".dropdown-submenu > a:after {\r\n");
      out.write("  border-color: transparent transparent transparent #333;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border-width: 5px 0 5px 5px;\r\n");
      out.write("  content: \" \";\r\n");
      out.write("  display: block;\r\n");
      out.write("  float: right;  \r\n");
      out.write("  height: 0;     \r\n");
      out.write("  margin-right: -10px;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("  width: 0;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dropdown-submenu:hover>a:after {\r\n");
      out.write("    border-left-color:#555;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu > li > a:hover, .dropdown-menu > .active > a:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}  \r\n");
      out.write("  \r\n");
      out.write("@media (max-width: 767px) {\r\n");
      out.write("  .navbar-nav  {\r\n");
      out.write("     display: inline;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-brand {\r\n");
      out.write("    display: inline;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-toggle .icon-bar {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-nav .dropdown-menu > li > a {\r\n");
      out.write("    color: red;\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    margin-top: 2px;   \r\n");
      out.write("  }\r\n");
      out.write("   .navbar-default .navbar-nav .open .dropdown-menu > li > a {\r\n");
      out.write("     color: #333;\r\n");
      out.write("   }\r\n");
      out.write("   .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,\r\n");
      out.write("   .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {\r\n");
      out.write("     background-color: #ccc;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   .navbar-nav .open .dropdown-menu {\r\n");
      out.write("     border-bottom: 1px solid white; \r\n");
      out.write("     border-radius: 0;\r\n");
      out.write("   }\r\n");
      out.write("  .dropdown-menu {\r\n");
      out.write("      padding-left: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  .dropdown-menu .dropdown-menu {\r\n");
      out.write("      padding-left: 20px;\r\n");
      out.write("   }\r\n");
      out.write("   .dropdown-menu .dropdown-menu .dropdown-menu {\r\n");
      out.write("      padding-left: 30px;\r\n");
      out.write("   }\r\n");
      out.write("   li.dropdown.open {\r\n");
      out.write("    border: 0px solid red;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("@media (min-width: 768px) {\r\n");
      out.write("  ul.nav li:hover > ul.dropdown-menu {\r\n");
      out.write("    display: block;\r\n");
      out.write("  }\r\n");
      out.write("  #navbar {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"navbar\">\r\n");
      out.write("  <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-1\">\r\n");
      out.write("      <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">Brand</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbar-collapse-1\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"#\">Active Link</a></li>\r\n");
      out.write("        <li><a href=\"#\">Link</a></li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a> \r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li class=\"kopie\"><a href=\"#\">Dropdown</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown Link 1</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">Dropdown Link 2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown Link 3</a></li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Link 4</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown Link 4</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.3</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.4</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Link 5</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown Link 5</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 5.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 5.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 5.3</a></li>\r\n");
      out.write("                <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Submenu Link 5.4</a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li class=\"kopie\"><a href=\"#\">Dropdown Submenu Link 5.4</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown Submenu Link 5.4.1</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown Submenu Link 5.4.2</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown2 <b class=\"caret\"></b></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li class=\"kopie\"><a href=\"#\">Dropdown2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown2 Link 1</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown2 Link 2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown2 Link 3</a></li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown2 Link 4</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown2 Link 4</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.3</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.4</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown2 Link 5</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown Link 5</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 5.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 5.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 5.3</a></li>\r\n");
      out.write("                <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Submenu Link 5.4</a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li class=\"kopie\"><a href=\"#\">Dropdown2 Submenu Link 5.4</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown2 Submenu Link 5.4.1</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown2 Submenu Link 5.4.2</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.navbar-collapse -->\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <form action=\"validate\">\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"email\"><span class=\"glyphicon glyphicon-envelope\">Email:</label>\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Enter email\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"pwd\">Password:</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pwd\" placeholder=\"Enter password\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"checkbox\">\r\n");
      out.write("      <label><input type=\"checkbox\"> Remember me</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
