/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-04-20 11:30:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/CommonHeader.jsp", Long.valueOf(1492687799375L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1491558854992L));
    _jspx_dependants.put("jar:file:/F:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WheelskartFrontEnd/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\t\t<h2>Welcome to Shopping Cart</h2>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>\r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write(".dropdown-menu > li.kopie > a {\r\n");
      out.write("    padding-left:5px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dropdown-submenu {\r\n");
      out.write("    position:relative;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-submenu>.dropdown-menu {\r\n");
      out.write("   top:0;left:100%;\r\n");
      out.write("   margin-top:-6px;margin-left:-1px;\r\n");
      out.write("   -webkit-border-radius:0 6px 6px 6px;-moz-border-radius:0 6px 6px 6px;border-radius:0 6px 6px 6px;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(".dropdown-submenu > a:after {\r\n");
      out.write("  border-color: transparent transparent transparent #333;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border-width: 5px 0 5px 5px;\r\n");
      out.write("  content: \" \";\r\n");
      out.write("  display: block;\r\n");
      out.write("  float: right;  \r\n");
      out.write("  height: 0;     \r\n");
      out.write("  margin-right: -10px;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("  width: 0;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dropdown-submenu:hover>a:after {\r\n");
      out.write("    border-left-color:#555;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu > li > a:hover, .dropdown-menu > .active > a:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}  \r\n");
      out.write("  \r\n");
      out.write("@media (max-width: 767px) {\r\n");
      out.write("  .navbar-nav  {\r\n");
      out.write("     display: inline;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-brand {\r\n");
      out.write("    display: inline;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-toggle .icon-bar {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-nav .dropdown-menu > li > a {\r\n");
      out.write("    color: red;\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    margin-top: 2px;   \r\n");
      out.write("  }\r\n");
      out.write("   .navbar-default .navbar-nav .open .dropdown-menu > li > a {\r\n");
      out.write("     color: #333;\r\n");
      out.write("   }\r\n");
      out.write("   .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,\r\n");
      out.write("   .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {\r\n");
      out.write("     background-color: #ccc;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   .navbar-nav .open .dropdown-menu {\r\n");
      out.write("     border-bottom: 1px solid white; \r\n");
      out.write("     border-radius: 0;\r\n");
      out.write("   }\r\n");
      out.write("  .dropdown-menu {\r\n");
      out.write("      padding-left: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  .dropdown-menu .dropdown-menu {\r\n");
      out.write("      padding-left: 20px;\r\n");
      out.write("   }\r\n");
      out.write("   .dropdown-menu .dropdown-menu .dropdown-menu {\r\n");
      out.write("      padding-left: 30px;\r\n");
      out.write("   }\r\n");
      out.write("   li.dropdown.open {\r\n");
      out.write("    border: 0px solid red;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("@media (min-width: 768px) {\r\n");
      out.write("  ul.nav li:hover > ul.dropdown-menu {\r\n");
      out.write("    display: block;\r\n");
      out.write("  }\r\n");
      out.write("  #navbar {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"navbar\">\r\n");
      out.write("  <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-1\">\r\n");
      out.write("      <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">Brand</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbar-collapse-1\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"#\">Active Link</a></li>\r\n");
      out.write("        <li><a href=\"#\">Link</a></li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a> \r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li class=\"kopie\"><a href=\"#\">Dropdown</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown Link 1</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">Dropdown Link 2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown Link 3</a></li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Link 4</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown Link 4</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.3</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 4.4</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Link 5</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown Link 5</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 5.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 5.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown Submenu Link 5.3</a></li>\r\n");
      out.write("                <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Submenu Link 5.4</a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li class=\"kopie\"><a href=\"#\">Dropdown Submenu Link 5.4</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown Submenu Link 5.4.1</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown Submenu Link 5.4.2</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown2 <b class=\"caret\"></b></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li class=\"kopie\"><a href=\"#\">Dropdown2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown2 Link 1</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown2 Link 2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Dropdown2 Link 3</a></li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown2 Link 4</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown2 Link 4</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.3</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 4.4</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown2 Link 5</a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li class=\"kopie\"><a href=\"#\">Dropdown Link 5</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 5.1</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 5.2</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dropdown2 Submenu Link 5.3</a></li>\r\n");
      out.write("                <li class=\"dropdown dropdown-submenu\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown Submenu Link 5.4</a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li class=\"kopie\"><a href=\"#\">Dropdown2 Submenu Link 5.4</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown2 Submenu Link 5.4.1</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Dropdown2 Submenu Link 5.4.2</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.navbar-collapse -->\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<hr color=\"blue\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"LoginPage\"> Login</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"RegistrationPage\"> Register</a>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /Home.jsp(28,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isUserClickedLogin=='true'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/views/Login.jsp", out, false);
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /Home.jsp(35,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isUserClickedRegister=='true' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/views/Registration.jsp", out, false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
